// Generated by CoffeeScript 1.4.0
(function() {
  'use strict';

  var $, app;

  $ = require('jquery-browserify');

  app = angular.module('app', []);

  app.controller('LoginFormCtrl', [
    '$scope', function($scope) {
      var isInvalid;
      $scope.signIn = function() {};
      isInvalid = function(field) {
        var input;
        input = $scope.loginForm[field];
        return !input.$pristine && input.$invalid;
      };
      $scope.isInvalidLogin = function() {
        return isInvalid('login');
      };
      return $scope.isInvalidPassword = function() {
        return isInvalid('password');
      };
    }
  ]);

}).call(this);
