// Generated by CoffeeScript 1.4.0
(function() {
  'use strict';

  app.controller('SignUpCtrl', [
    '$scope', '$http', function(s, $http) {
      s.doValidate = false;
      s.checkRepeatePassword = function() {
        var error;
        if (s.signUpForm.repeatPassword.$pristine) {
          return;
        }
        if (s.signUpForm.password.$error.required) {
          return;
        }
        if (s.signUpForm.repeatePassword.$error.required) {
          return;
        }
        error = s.user.repeatPassword === s.user.password;
        s.signUpForm.$error.repeatPassword = error;
        return s.signUpForm.repeatePassword.$error.repeatPassword = error;
      };
      return s.signUp = function() {
        s.doValidate = true;
        if (s.signUpForm.$invalid) {
          return showErrors();
        }
        return $http.post('/signIn', s.user).success(function(response) {
          if (response.error) {
            return console.error(response.errorMessage);
          }
          return location.reload();
        }).error(function(response) {
          return console.error(response);
        });
      };
    }
  ]);

}).call(this);
